name: build-bbiribarabu

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y libasound2-dev pkg-config
      - run: cargo build --release
      - run: mv target/release/Bbiribarabu bbiribarabu-linux
      - uses: softprops/action-gh-release@v1
        with:
          files: bbiribarabu-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build macOS binary
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build macOS release binary
        run: |
          MACOSX_DEPLOYMENT_TARGET=13.0 cargo build --release
      - run: mv target/release/Bbiribarabu bbiribarabu-macos
      - uses: softprops/action-gh-release@v1
        with:
          files: bbiribarabu-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
